### ISSUE TITLE
create env variable to set extendedTypesEnabled and emulate353TTLNodes

### ISSUE THREAD

**Issue by kwonglau** [31z4/zookeeper-docker#109]
zookeeper only allow enabling these 2 configuration params using Java system property. The default is false for extendedTypesEnabled. When extendedTypesEnabled is not true. It throws exception when creating node with ttl and with CreateMode.PERSISTENT_WITH_TTL

https://zookeeper.apache.org/doc/r3.6.1/zookeeperCLI.html

### Expected behavior

If we are able to pass "-Dzookeeper.extendedTypesEnabled=true -Dzookeeper.emulate353TTLNodes=true" to the zkServer.sh, zookeeper will not throw exception

### Actual behavior

Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /5bd2c018-2c12-40d9-bb87-fd205070b623/03273a3a-9c7f-44cc-9ede-1e85c77285fc
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1836)
	at org.apache.curator.framework.imps.CreateBuilderImpl$16.call(CreateBuilderImpl.java:1131)
	at org.apache.curator.framework.imps.CreateBuilderImpl$16.call(CreateBuilderImpl.java:1113)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1110)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:593)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:583)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:48)

### System configuration

ref:
https://laptrinhx.com/zookeeper-getting-started-2735625383/

**Comment by 31z4** [comment]
You can pass Java system properties using `JVMFLAGS` environment variable:

```docker run -e JVMFLAGS="-Dzookeeper.extendedTypesEnabled=true -Dzookeeper.emulate353TTLNodes=true" zookeeper```

See Advanced configuration section in the image documentation: https://hub.docker.com/_/zookeeper/.

**Comment by kwonglau** [comment]
thanks! it works
