### ISSUE TITLE
ZOO_MY_ID not used by zookeeper

### ISSUE THREAD

**Issue by jmwilkinson** [31z4/zookeeper-docker#13]
Documentation states:

> ZOO_MY_ID
> The id must be unique within the ensemble and should have a value between 1 and 255. Do note that this variable will not have any effect if you start the container with a /data directory that already contains the myid file.

However, starting zookeeper with that ENV (-e ZOO_MY_ID=1):

```
2017-05-18 17:00:26,613 [myid:] - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /conf/zoo.cfg
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:154)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.IllegalArgumentException: /var/lib/zookeeper/myid file is missing
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:406)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
	... 2 more
```

And for verification:
```
bash-4.3# echo $ZOO_MY_ID
1
bash-4.3#
```

Either Zookeeper is not using the ZOO_MY_ID env variable, or the documentation is missing a key piece of information for starting zookeeper.

**Comment by 31z4** [comment]
Thank you for your report @jmwilkinson 
`ZOO_MY_ID` works just fine out of the box

**Comment by 31z4** [comment]
Hey @jmwilkinson was the issue solved somehow?

**Comment by jmwilkinson** [comment]
Hey @31z4 

Sorry for the delayed response.

I already had the dataDir specified in my config (pointing to a non-default location). I solved the problem by writing the id directly to the `myid` file, and then starting zookeeper.

**Comment by 31z4** [comment]
Alright! So I'm closing this.

**Comment by jmwilkinson** [comment]
Ok. To be clear, this is still a bug somewhere- though perhaps with zookeeper and not the docker build.
