### ISSUE TITLE
Fails to Connect to Port 3888

### ISSUE THREAD

**Issue by zanes2016** [31z4/zookeeper-docker#35]
I suspect this is a simple misconfiguration on my part, but for some reason zookeeper 3.5 isn't listening on 3888 and won't come up as an ensemble.

The only configuration change I've done to upgrade from 3.4 to 3.5 is edited the `ZOO_SERVERS` environment variable.

Check Port Connection:
```
$ telnet 172.27.1.35 3888
Trying 172.27.1.35...
telnet: Unable to connect to remote host: Connection refused
```

Logs (this is the same for each host/zk instance):
```
$ docker logs zookeeper
...
2018-02-27 17:52:10,613 [myid:5] - WARN  [WorkerSender[myid=5]:QuorumCnxManager@457] - Cannot open channel to 4 at election address /172.27.1.35:3888
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:443)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:486)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:421)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:486)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:465)
	at java.lang.Thread.run(Thread.java:748)
...
```

Docker Configuration:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                            NAMES
b57bc2ce1be9        zookeeper:3.5       "/docker-entrypoin..."   6 minutes ago       Up 6 minutes        0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp, 0.0.0.0:8080->8080/tcp   zookeeper
$ docker inspect zookeeper
[
    {
        "Id": "b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016",
        "Created": "2018-02-27T17:48:24.112542148Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "zkServer.sh",
            "start-foreground"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2976,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-02-27T17:48:24.442237938Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:21141b14d33ee38abb97b37645e185e8922839b1f7d2d538ac07f75e47f79269",
        "ResolvConfPath": "/var/lib/docker/containers/b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016/hostname",
        "HostsPath": "/var/lib/docker/containers/b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016/hosts",
        "LogPath": "/var/lib/docker/containers/b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016/b57bc2ce1be97b1da2d41fce1a22e27d815ee0e6162e371da8411ca6d14fe016-json.log",
        "Name": "/zookeeper",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "2181/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2181"
                    }
                ],
                "2888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2888"
                    }
                ],
                "3888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3888"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "Tmpfs": {
                "/data": "rw,size=1G"
            },
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/18858c553feee2d0340cf102411206db072a11cedb33e7f089545c18397fd6e6-init/diff:/var/lib/docker/overlay2/759cb40e5abea1383926f56fca033df56f258b565ba5d2d308e88974ac134bc9/diff:/var/lib/docker/overlay2/87d1ce537310cec8c9519c1b891e06a71cf4c85194a4dacc1bfaeb07d3c11d66/diff:/var/lib/docker/overlay2/13254cf8a41fbb5c96e97b33e134f436bee3124e1ecf48ae4d1f44935d07074e/diff:/var/lib/docker/overlay2/e089d7d80aba98cb204320ad0dd43def9452b1c05d5134faffbf9aa27730ef5e/diff:/var/lib/docker/overlay2/b5a31c87f007cbfc63fa4e810bc2a925a6cbf2f9952a4769439cdec4e3d17824/diff:/var/lib/docker/overlay2/b50150ec0f99701848dc38a3e7b72ff1ec89603b64c4dd1cf9857a6546a19875/diff:/var/lib/docker/overlay2/962303bcabf8087dd8485b0c7cfca5682bef37e6b7ce30d552672d8171c3b215/diff",
                "MergedDir": "/var/lib/docker/overlay2/18858c553feee2d0340cf102411206db072a11cedb33e7f089545c18397fd6e6/merged",
                "UpperDir": "/var/lib/docker/overlay2/18858c553feee2d0340cf102411206db072a11cedb33e7f089545c18397fd6e6/diff",
                "WorkDir": "/var/lib/docker/overlay2/18858c553feee2d0340cf102411206db072a11cedb33e7f089545c18397fd6e6/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "654db3b70d80482433a019e56dcee9e50ab45407b895469bf97cf5ef33206ddc",
                "Source": "/var/lib/docker/volumes/654db3b70d80482433a019e56dcee9e50ab45407b895469bf97cf5ef33206ddc/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "679dc5839d62c11866f17e50f383aa691f4d1f585b31429bcd3e207af78aee3c",
                "Source": "/var/lib/docker/volumes/679dc5839d62c11866f17e50f383aa691f4d1f585b31429bcd3e207af78aee3c/_data",
                "Destination": "/datalog",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "zk5",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "2181/tcp": {},
                "2888/tcp": {},
                "3888/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ZOO_DATA_DIR=/data",
                "ZOO_MY_ID=5",
                "ZOO_SERVERS=server.1=172.27.1.140:2888:3888;2181 server.2=172.27.1.152:2888:3888;2181 server.3=172.27.1.217:2888:3888;2181 server.4=172.27.1.35:2888:3888;2181 server.5=0.0.0:2888:3888;2181",
                "ZOO_DATA_LOG_DIR=/datalog",
                "ZOO_CONF_DIR=/conf",
                "ZOO_TICK_TIME=2000",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin:/zookeeper-3.5.3-beta/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
                "JAVA_VERSION=8u151",
                "JAVA_ALPINE_VERSION=8.151.12-r0",
                "ZOO_USER=zookeeper",
                "ZOO_PORT=2181",
                "ZOO_INIT_LIMIT=5",
                "ZOO_SYNC_LIMIT=2",
                "ZOO_MAX_CLIENT_CNXNS=60",
                "ZOO_STANDALONE_ENABLED=false",
                "ZOOCFGDIR=/conf"
            ],
            "Cmd": [
                "zkServer.sh",
                "start-foreground"
            ],
            "ArgsEscaped": true,
            "Image": "zookeeper:3.5",
            "Volumes": {
                "/data": {},
                "/datalog": {}
            },
            "WorkingDir": "/zookeeper-3.5.3-beta",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ee46414fa83fe7299001cd953ca45d02b92f54579d3cf28d2009faae4dfd7b82",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "2181/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2181"
                    }
                ],
                "2888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2888"
                    }
                ],
                "3888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3888"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/ee46414fa83f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "4bb987d2a7459c37b192dba464cb8dacbbab1baffb3f1a710903e72a9149364e",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d2906d74e9ae1490b4166d1f04c8f897b3f622aaf9a9c52910f6b01a9a0b35c6",
                    "EndpointID": "4bb987d2a7459c37b192dba464cb8dacbbab1baffb3f1a710903e72a9149364e",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by 31z4** [comment]
Hello @zanes2016 Have you checked an example [`stack.yml`](https://github.com/31z4/zookeeper-docker#-via-docker-stack-deploy-or-docker-compose)? One notable difference is that you're using IP addresses in `ZOO_SERVERS`. Please try to use docker container names instead.

**Comment by zanes2016** [comment]
Thanks, but I did give the stack.yml file a look and used that as an initial reference. Zookeeper is being deployed by [Ansible](https://www.ansible.com/), so IP addresses are actually the easiest way to configure the zk instances across the multi-node cluster (unless anyone has any better suggestions).

@31z4 Are you suggesting that IP addresses are not explicitly supported?

As mentioned above, the only change i've made upgrading from **3.4** to **3.5** is reformatting the `ZOO_SERVERS` variable.

**3.5 ZOO_SERVERS:**
```
"ZOO_SERVERS=server.1=172.27.1.140:2888:3888;2181 server.2=172.27.1.152:2888:3888;2181 server.3=172.27.1.217:2888:3888;2181 server.4=172.27.1.35:2888:3888;2181 server.5=0.0.0:2888:3888;2181"
```

**3.4 ZOO_SERVERS:**
```
"ZOO_SERVERS=server.1=172.27.1.108:2888:3888 server.2=172.27.1.112:2888:3888 server.3=172.27.1.137:2888:3888 server.4=172.27.1.83:2888:3888 server.5=0.0.0.0:2888:3888"
```

**Comment by 31z4** [comment]
@zanes2016 I mean, are you sure that the IP addresses of the Zookeeper nodes remained the same when you restarted it with the `3.5` image?

As I see from your `docker inspect zookeeper` output the 5th node has `"IPAddress": "172.17.0.2"` which is a subnet that is different from the rest of the nodes (e.g. `172.27.1.83`). Are you sure that the nodes can reach each other?

**Comment by spanktar** [comment]
I'm having a similar issue with 3.4.x. The container can't bind to the port for some reason and it's baffling me because it binds to 2181 no problem.  I found [this post](https://container-solutions.com/dynamic-zookeeper-cluster-with-docker/) but adding --net=host didn't solve it either.

The command and config are super simple:
```
docker run \
  --name zookeeper \
  --network="host" \
  --restart always \
  -e "SERVICE_2181_NAME=zookeeper" \
  -v /etc/zookeeper/zoo.cfg:/conf/zoo.cfg \
zookeeper
```

and zoo.cfg has the basics:
```
tickTime=2000
initLimit=9
syncLimit=6
dataDir=/data
dataLogDir=/datalog
clientPort=2181
#maxClientCnxns=60
autopurge.snapRetainCount=3
autopurge.purgeInterval=168
standaloneEnabled=false
server.0=10.0.10.156:2888:3888
server.1=10.0.10.171:2888:3888
server.2=10.0.10.214:2888:3888
```

The error I see from the container logs:

```
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
2018-10-25 12:43:06,715 [myid:] - INFO  [main:QuorumPeerConfig@136] - Reading configuration from: /conf/zoo.cfg
2018-10-25 12:43:06,729 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.0.10.214 to address: /10.0.10.214
2018-10-25 12:43:06,729 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.0.10.171 to address: /10.0.10.171
2018-10-25 12:43:06,730 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.0.10.156 to address: /10.0.10.156
2018-10-25 12:43:06,730 [myid:] - INFO  [main:QuorumPeerConfig@398] - Defaulting to majority quorums
2018-10-25 12:43:06,734 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-10-25 12:43:06,734 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 168
2018-10-25 12:43:06,739 [myid:1] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
2018-10-25 12:43:06,752 [myid:1] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
2018-10-25 12:43:06,752 [myid:1] - INFO  [main:QuorumPeerMain@130] - Starting quorum peer
2018-10-25 12:43:06,764 [myid:1] - INFO  [main:ServerCnxnFactory@117] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
2018-10-25 12:43:06,770 [myid:1] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-10-25 12:43:06,772 [myid:1] - INFO  [main:QuorumPeer@1158] - tickTime set to 2000
2018-10-25 12:43:06,772 [myid:1] - INFO  [main:QuorumPeer@1204] - initLimit set to 9
2018-10-25 12:43:06,772 [myid:1] - INFO  [main:QuorumPeer@1178] - minSessionTimeout set to -1
2018-10-25 12:43:06,772 [myid:1] - INFO  [main:QuorumPeer@1189] - maxSessionTimeout set to -1
2018-10-25 12:43:06,781 [myid:1] - INFO  [main:QuorumPeer@1467] - QuorumPeer communication is not secured!
2018-10-25 12:43:06,781 [myid:1] - INFO  [main:QuorumPeer@1496] - quorum.cnxn.threads.size set to 20
2018-10-25 12:43:06,783 [myid:1] - INFO  [main:QuorumPeer@668] - currentEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2018-10-25 12:43:06,787 [myid:1] - INFO  [main:QuorumPeer@683] - acceptedEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2018-10-25 12:43:06,793 [myid:1] - INFO  [ListenerThread:QuorumCnxManager$Listener@736] - My election bind port: /10.0.10.171:3888
2018-10-25 12:43:06,794 [myid:1] - ERROR [/10.0.10.171:3888:QuorumCnxManager$Listener@760] - Exception while listening
java.net.BindException: Address not available (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.bind(ServerSocket.java:329)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:739)
2018-10-25 12:43:06,802 [myid:1] - INFO  [QuorumPeer[myid=1]/0:0:0:0:0:0:0:0:2181:QuorumPeer@909] - LOOKING
2018-10-25 12:43:06,803 [myid:1] - INFO  [QuorumPeer[myid=1]/0:0:0:0:0:0:0:0:2181:FastLeaderElection@813] - New election. My id =  1, proposed zxid=0x0
2018-10-25 12:43:06,807 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@584] - Cannot open channel to 0 at election address /10.0.10.156:3888
```

From what I can tell, it's trying to bind 3888 to the host IP, when in a container it should bind to localhost/the container IP, right?  Same error if I don't use --net=host and map ports.

Any help is appreciated as right now I can't seem to establish a cluster using this container.

**Comment by xwqb** [comment]
At present most of the cloud server not card, I think it's about 3888 without listening to the cause of the network card, ` docker - entrypoint. Sh ` should add an environment variable user Settings to monitor all ports, such as: ` echo "syncLimit = $ZOO_QUO_ALL" > > "$CONFIG" `, is used to set on all interfaces, to 3888

`clientPort=2181
dataDir=/home/zookeeper1/data
dataLogDir=/home/zookeeper1/datalog
tickTime=2000
initLimit=5
syncLimit=2
autopurge.snapRetainCount=3
autopurge.purgeInterval=0
maxClientCnxns=60
_quorumListenOnAllIPs=true_
server.1=server1:2888:3888
server.2=server1:2889:3889
server.3=server1:2888:3888`

**Comment by muhlemmer** [comment]
Hi, I'm having the same issue with below docker-compose.yml, running on docker Swarm. I am using docker host-names, but no success.

```
version: '3.7'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == d1.host.com
      restart_policy:
        condition: any

  zoo2:
    image: zookeeper
    hostname: zoo2
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == d2.host.com
      restart_policy:
        condition: any

  zoo3:
    image: zookeeper
    hostname: zoo3
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == d3.host.com
      restart_policy:
        condition: any

networks:
  zoo:
```

**Comment by muhlemmer** [comment]
> At present most of the cloud server not card, I think it's about 3888 without listening to the cause of the network card, `docker - entrypoint. Sh` should add an environment variable user Settings to monitor all ports, such as: `echo "quorumListenOnAllIP= $ZOO_QUO_ALL" > > "$CONFIG"`, is used to set on all interfaces, to 3888
> 
> ```
> clientPort=2181
> dataDir=/home/zookeeper1/data
> dataLogDir=/home/zookeeper1/datalog
> tickTime=2000
> initLimit=5
> syncLimit=2
> autopurge.snapRetainCount=3
> autopurge.purgeInterval=0
> maxClientCnxns=60
> #this set
> quorumListenOnAllIPs=true
> server.1=server1:2888:3888
> server.2=server1:2889:3889
> server.3=server1:2888:3888
> ```

Note there was a typo in the echo command. Regardless, I've tried the suggestion by modifying `docker-entypoint.sh`, rebuilding and `docker stack deploy`.

So in entry point:
```
echo "quorumListenOnAllIPs=$ZOO_QUO_ALL" >> "$CONFIG"
```
I've set `ZOO_QUO_ALL: 'true'` in `docker-compose.yml`. And after deploy I inspected `/conf/zoo.cfg`:
```
clientPort=2181
dataDir=/data
dataLogDir=/datalog
tickTime=2000
initLimit=5
syncLimit=2
autopurge.snapRetainCount=3
autopurge.purgeInterval=0
maxClientCnxns=60
quorumListenOnAllIPs=true
server.1=0.0.0.0:2888:3888
server.2=zoo2:2888:3888
server.3=zoo3:2888:3888
```
Still doesn't work... Some logs:
```
2019-04-26 14:25:57,849 [myid:1] - WARN  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumCnxManager@584] - Cannot open channel to 3 at election address zoo3/10.0.14.2:3888
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610)
        at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:958)
2019-04-26 14:25:57,851 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@185] - Resolved hostname: zoo3 to address: zoo3/10.0.14.2
2019-04-26 14:25:57,851 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FastLeaderElection@847] - Notification time out: 60000
```
From inside container `zoo1`:
```
bash-4.4# ping zoo1
PING zoo1 (10.0.14.6): 56 data bytes
64 bytes from 10.0.14.6: seq=0 ttl=64 time=0.151 ms
64 bytes from 10.0.14.6: seq=1 ttl=64 time=0.108 ms
^C
--- zoo1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.108/0.129/0.151 ms

bash-4.4# ping zoo2
PING zoo2 (10.0.14.8): 56 data bytes
64 bytes from 10.0.14.8: seq=0 ttl=64 time=0.281 ms
64 bytes from 10.0.14.8: seq=1 ttl=64 time=0.126 ms
^C
--- zoo2 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.126/0.203/0.281 ms

bash-4.4# ping zoo3
PING zoo3 (10.0.14.2): 56 data bytes
64 bytes from 10.0.14.2: seq=0 ttl=64 time=0.122 ms
64 bytes from 10.0.14.2: seq=1 ttl=64 time=0.094 ms
^C
--- zoo3 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.094/0.108/0.122 ms

bash-4.4# netstat -plutn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:44129        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:34763           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3888            0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:37778        0.0.0.0:*                           -
```

**Comment by muhlemmer** [comment]
I'm almost sure this has to do with Docker's overlay network VIP endpoint mode. Where every service gets put behind a virtual IP. Using `endpoint_mode: dnsrr`, Zookeeper works just fine. [Docker documentation](https://docs.docker.com/compose/compose-file/#endpoint_mode). The docs say that endpoint mode only works in compose v3.3, but I think that's an error. It works fine in my v3.7 file.

My working `stack.yml` file:
```
version: '3.7'

services:
  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == api0.usrp.ro
      restart_policy:
        condition: any

  zoo2:
    image: zookeeper:3.4
    hostname: zoo2
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == api1.usrp.ro
      restart_policy:
        condition: any

  zoo3:
    image: zookeeper:3.4
    hostname: zoo3
    networks:
      - zoo
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.hostname == api2.usrp.ro
      restart_policy:
        condition: any

networks:
  zoo:
```

**Comment by JohnChancfz** [comment]
zoo3_1  | 2019-10-01 18:48:19,117 [myid:3] - INFO  [main:DefaultSessionIdManager@370] - No SessionScavenger set, using defaults
zoo1_1  | 2019-10-01 18:48:19,113 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@677] - Cannot open channel to 2 at election address zoo2/172.19.0.2:3888
zoo1_1  | java.net.ConnectException: Connection refused (Connection refused)
zoo1_1  | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
zoo1_1  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
zoo1_1  | 	at java.net.Socket.connect(Socket.java:589)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:648)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:705)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:618)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:477)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:456)
zoo1_1  | 	at java.lang.Thread.run(Thread.java:748)
zoo3_1  | 2019-10-01 18:48:19,119 [myid:3] - INFO  [main:HouseKeeper@149] - node0 Scavenging every 660000ms
zoo1_1  | 2019-10-01 18:48:19,119 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@677] - Cannot open channel to 3 at election address zoo3/172.19.0.3:3888
zoo1_1  | java.net.ConnectException: Connection refused (Connection refused)
zoo1_1  | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
zoo1_1  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
zoo1_1  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
zoo1_1  | 	at java.net.Socket.connect(Socket.java:589)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:648)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:705)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:618)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:477)
zoo1_1  | 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:456)
zoo1_1  | 	at java.lang.Thread.run(Thread.java:748)
zoo1_1  | 2019-10-01 18:48:19,121 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@679] - Notification: 2 (message format version), 1 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x1 (n.peerEPoch), LOOKING (my state)0 (n.config version)

**Comment by 31z4** [comment]
There's some chance #84 might help.

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
